# Generated by Django 4.2.7 on 2023-12-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
            ],
        ),
    ]
